name: CI

on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    runs-on: python  # 更正为合适的 runner

    steps:
      - uses: actions/checkout@v4

      - name: Run test
        id: run_test  # 添加一个 ID 用于引用
        run: |
          output=$(echo 'python3 src/main.py' && echo "Test done.")
          echo "::set-output name=result::$output"

      - name: Error report status on Feishu
        if: ${{ failure() }}  # 仅在失败时执行
        run: |
          echo "Test failed. Starting error report..."
          # 在这里添加发送错误报告的命令
          sh -c "python3 /opt/public_scripts/feishu_webhook_bot_sre_group.py 'Failed' 'red' '${{ github.ref_name }} - ${{ github.run_id }}' '${{ steps.run_test.outputs.result }}' '${{ github.ref }}' "

      - name: Success report status on Feishu
        if: ${{ success() }}  # 仅在成功时执行
        run: |
          echo "Test succeeded. Starting success report..."
          # 在这里添加发送成功报告的命令
          sh -c "python3 /opt/public_scripts/feishu_webhook_bot_sre_group.py 'Succeed' 'green' '${{ github.ref_name }} - ${{ github.run_id }}' '${{ steps.run_test.outputs.result }}' '${{ github.ref }}' "
